//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtividadeEntrevista.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Beneficiario
    {
        public long Id { get; set; }
        public string CPF { get; set; }
        public string Nome { get; set; }
        public long IdCliente { get; set; }
    
        public virtual Cliente Cliente { get; set; }
    }
}
